### ISSUE TITLE
Error: 'responseCallback' must be a function

### ISSUE THREAD

**Issue by manuel-di-iorio** [ImpressTV/loadtester#1]
After installing this module and running your test code:

``` cmd
Error: 'responseCallback' must be a function
    at Error (native)
    at new LoadTester (C:\Users\Manuel\Desktop\node_modules\loadtester\lib\loadtester.js:45:11)
    at Object.<anonymous> (C:\Users\Manuel\Desktop\index.js:5:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3
```

Easily fixed by providing a callback, but that was not obvious.

---

Another small error:

``` cmd
loadTester.start();

ReferenceError: loadTester is not defined
    at Object.<anonymous> (C:\Users\Manuel\Desktop\index.js:12:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3
```

---

Latest error I found - It happens after I hit Ctrl+C:

``` cmd
C:\Users\Manuel\Desktop\node_modules\loadtester\lib\stat-functions.js:5
    return {min: dataSet[0].value};
                           ^
TypeError: Cannot read property 'value' of undefined
    at functions.min (C:\Users\Manuel\Desktop\node_modules\loadtester\lib\stat-functions.js:5:28)
    at C:\Users\Manuel\Desktop\node_modules\loadtester\lib\counter.js:80:70
    at Array.forEach (native)
    at calculateMetrics (C:\Users\Manuel\Desktop\node_modules\loadtester\lib\counter.js:75:59)
    at stats (C:\Users\Manuel\Desktop\node_modules\loadtester\lib\loadtester.js:152:32)
    at process.<anonymous> (C:\Users\Manuel\Desktop\index.js:22:39)
    at emitNone (events.js:67:13)
    at process.emit (events.js:166:7)
    at Signal.wrap.onsignal (node.js:804:46)
```

**Comment by martonw** [comment]
Hi - thanks for your comments it was indeed broken somehow. The first 2 issues mentioned are patched now. The last one would not show up if you replace 'http://localhost/my/app/to/test' to something existing in your environment. (I agree it is not nice that you get an error anyway; if I will have a bit of time I will improve the error handling).
